import { Household, Task, Template, Badge } from '@/types';

export const createMockHousehold = (): Household => ({
  id: 'household-1',
  name: 'The Clark Family',
  managerId: 'member-1',
  members: [
    {
      id: 'member-1',
      name: 'Zara',
      role: 'manager',
      avatar: '👩‍💼',
      points: 450,
      tasksCompleted: 23,
      color: '#8B5CF6',
    },
    {
      id: 'member-2',
      name: 'Marcus',
      role: 'member',
      avatar: '👨‍💼',
      points: 380,
      tasksCompleted: 19,
      color: '#3B82F6',
    },
    {
      id: 'member-3',
      name: 'Emma',
      role: 'child',
      avatar: '👧',
      points: 220,
      tasksCompleted: 11,
      color: '#EC4899',
    },
  ],
});

export const createMockTasks = (): Task[] => [
  {
    id: 'task-1',
    title: 'Laundry',
    description: 'Wash, dry, and fold all laundry',
    assigneeId: 'member-2',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'todo',
    recurrence: 'weekly',
    room: 'Laundry Room',
    points: 30,
    createdBy: 'member-1',
    createdAt: new Date().toISOString(),
    estimatedMinutes: 90,
  },
  {
    id: 'task-2',
    title: 'Grocery Shopping',
    description: 'Weekly grocery run - check list in notes',
    assigneeId: 'member-1',
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'in-progress',
    recurrence: 'weekly',
    room: 'Kitchen',
    points: 40,
    createdBy: 'member-1',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    estimatedMinutes: 120,
  },
  {
    id: 'task-3',
    title: 'Clean Room',
    description: 'Tidy up bedroom and put toys away',
    assigneeId: 'member-3',
    dueDate: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    status: 'todo',
    recurrence: 'daily',
    room: 'Bedroom',
    points: 15,
    createdBy: 'member-1',
    createdAt: new Date().toISOString(),
    estimatedMinutes: 30,
  },
  {
    id: 'task-4',
    title: 'Vacuum Living Room',
    description: 'Vacuum all carpets and under furniture',
    assigneeId: 'member-2',
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'done',
    recurrence: 'weekly',
    room: 'Living Room',
    points: 25,
    createdBy: 'member-1',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedMinutes: 45,
  },
  {
    id: 'task-5',
    title: 'Take Out Trash',
    description: 'Empty all trash bins and take to curb',
    assigneeId: 'member-3',
    dueDate: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    status: 'todo',
    recurrence: 'weekly',
    room: 'Kitchen',
    points: 10,
    createdBy: 'member-2',
    createdAt: new Date().toISOString(),
    estimatedMinutes: 15,
  },
];

export const createMockTemplates = (): Template[] => [
  {
    id: 'template-1',
    name: 'Travel Prep',
    category: 'Travel',
    description: 'Complete checklist for family travel preparation',
    isCustom: false,
    tasks: [
      {
        title: 'Pack Suitcases',
        description: 'Pack clothes and essentials for everyone',
        dueDate: '',
        status: 'todo',
        recurrence: 'none',
        room: 'Bedroom',
        points: 30,
        createdBy: '',
        createdAt: '',
        estimatedMinutes: 120,
      },
      {
        title: 'Check Travel Documents',
        description: 'Verify passports, tickets, and reservations',
        dueDate: '',
        status: 'todo',
        recurrence: 'none',
        room: 'Office',
        points: 20,
        createdBy: '',
        createdAt: '',
        estimatedMinutes: 30,
      },
      {
        title: 'Arrange Pet Care',
        description: 'Confirm pet sitter or boarding',
        dueDate: '',
        status: 'todo',
        recurrence: 'none',
        room: 'General',
        points: 25,
        createdBy: '',
        createdAt: '',
        estimatedMinutes: 45,
      },
    ],
  },
  {
    id: 'template-2',
    name: 'Back to School',
    category: 'Education',
    description: 'Prepare for new school year',
    isCustom: false,
    tasks: [
      {
        title: 'Buy School Supplies',
        description: 'Purchase items from school supply list',
        dueDate: '',
        status: 'todo',
        recurrence: 'none',
        room: 'General',
        points: 35,
        createdBy: '',
        createdAt: '',
        estimatedMinutes: 90,
      },
      {
        title: 'Label All Items',
        description: 'Label lunch boxes, backpacks, and supplies',
        dueDate: '',
        status: 'todo',
        recurrence: 'none',
        room: 'General',
        points: 15,
        createdBy: '',
        createdAt: '',
        estimatedMinutes: 30,
      },
      {
        title: 'Set Up Study Space',
        description: 'Organize desk and homework area',
        dueDate: '',
        status: 'todo',
        recurrence: 'none',
        room: 'Bedroom',
        points: 20,
        createdBy: '',
        createdAt: '',
        estimatedMinutes: 60,
      },
    ],
  },
  {
    id: 'template-3',
    name: 'Spring Cleaning',
    category: 'Cleaning',
    description: 'Deep clean entire house',
    isCustom: false,
    tasks: [
      {
        title: 'Clean Windows',
        description: 'Wash all windows inside and out',
        dueDate: '',
        status: 'todo',
        recurrence: 'none',
        room: 'General',
        points: 40,
        createdBy: '',
        createdAt: '',
        estimatedMinutes: 120,
      },
      {
        title: 'Organize Closets',
        description: 'Sort and donate unused items',
        dueDate: '',
        status: 'todo',
        recurrence: 'none',
        room: 'Bedroom',
        points: 35,
        createdBy: '',
        createdAt: '',
        estimatedMinutes: 90,
      },
      {
        title: 'Deep Clean Kitchen',
        description: 'Clean appliances, cabinets, and pantry',
        dueDate: '',
        status: 'todo',
        recurrence: 'none',
        room: 'Kitchen',
        points: 45,
        createdBy: '',
        createdAt: '',
        estimatedMinutes: 150,
      },
    ],
  },
];

export const createMockBadges = (): Badge[] => [
  {
    id: 'badge-1',
    name: 'Task Master',
    description: 'Complete 10 tasks',
    icon: '🏆',
    threshold: 10,
    earnedBy: ['member-1', 'member-2', 'member-3'],
  },
  {
    id: 'badge-2',
    name: 'Team Player',
    description: 'Complete 25 tasks',
    icon: '⭐',
    threshold: 25,
    earnedBy: ['member-1'],
  },
  {
    id: 'badge-3',
    name: 'Consistency Champion',
    description: 'Complete tasks 7 days in a row',
    icon: '🔥',
    threshold: 7,
    earnedBy: ['member-1', 'member-2'],
  },
  {
    id: 'badge-4',
    name: 'Early Bird',
    description: 'Complete 5 tasks before due date',
    icon: '🌅',
    threshold: 5,
    earnedBy: ['member-2'],
  },
];